### ISSUE TITLE
Dependency version pins do not match upstream

### ISSUE THREAD

**Issue by timkpaine** [conda-forge/pylint-feedstock#93]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As title, there is a mismatch with the upstream dependencies specified in pylint. 

### Installed packages

```shell
N/A
```

### Environment info

```shell
All
```

**Comment by timkpaine** [comment]
Nvm looks like it's just the beta version

**Comment by wshanks** [comment]
Yes, between 2.14.x and the main branch they have switched to pyproject.toml and changed some other things. I checked that they matched before merging #92 today.
